# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: [main]
  create:

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Running JUnit Tests
      run: |
        mvn clean jacoco:prepare-agent install jacoco:report
        mvn clean test
        echo 'PRINT OUTPUT'
        pwd
        echo '>>>>>>>>>>>'
        ls -ltra target/


    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.6.1


    # - name: Publish to Docker image
    #   uses: mr-smithers-excellent/docker-build-push@v5
    #   with:
    #     image: kledockerhub/algorithm
    #     registry: docker.io
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
